### PR TITLE
Provision

### LINKED ISSUE #9: Provision command not functional

### PR DESCRIPTION
**Pull request by richardbporter**
This will resolve #9.

### CODE REVIEW

**Comment by brandonneil** [comment]
I think we still need to handle
- [ ] creating the external production domain, e.g. dining.uiowa.edu, and for subdirectory sites, this would fail gracefully with an exists message if it already exists. For instance, all the hawk sites, or for the housing.uiowa.edu/uhd-admin site after the housing.uiowa.edu site is provisioned, for instance.

**Comment by brandonneil** [comment]
Tested org sites and they miss their org part of the aliasGroup (above).
Tested studio and lab sites just fine.
Tested custom sites dsp.research.uiowa.edu just fine
Tested housing.uiowa.edu/uhd-admin and the domain stuff doesn't apply.

> In the uiowa701 site, you will create the custom_housing_uhd_admin database and the housing.dev.drupal.uiowa.edu/uhd-admin, housing.stage.drupal.uiowa.edu/uhd-admin, housing.prod.drupal.uiowa.edu/uhd-admin, housing.ra.drupal.uiowa.edu/uhd-admin domains. Are you sure you want to continue?

**Comment by richardbporter** [comment]
I created a separate issue for the org problem: #16. I can fix that separately.

I'll work on the prod domains.

**Comment by brandonneil** [comment]
Added new issue for subdirectory provisioning: #21

**Pull request merged**
