### PR TITLE
Docroot key

### PR DESCRIPTION
**Pull request by genjohnson**
This is intended to address https://github.com/ITS-UofIowa/nile/issues/123 - Allow the same URL on multiple docroots. 

Before this is merged, we will need to merge branch docroot_key of the drupal-manifest repo and revert commit 2a57bee here (so that we use the correct branch of the manifest).

### CODE REVIEW

**Comment by genjohnson** [comment]
You do not need to checkout the docroot_key branch of drupal-manifest to test this pull request.

**Comment by richardbporter** [comment]
I tested this out locally with a few commands and it looks good. My only question is whether we need to nest sites under a `sites:` key in the manifest anymore. I'm not sure it adds anything. Looping in @brandonneil for his input.

The new CloudUI and API is referring to sites as 'applications' now.

**Comment by brandonneil** [comment]
Perhaps `applications` is a better term. I think I still like the nesting for future use case of having other top-level attributes like metadata if we are so inclined.

**Comment by richardbporter** [comment]
Sounds good. Lets leave it like this until the CloudUI and API launch, and perhaps after #53

**Comment by richardbporter** [comment]
We'll need to coordinate a release with https://github.com/ITS-UofIowa/drupal-manifest/pull/149

**Pull request merged**
